title: px.iboard.cc
author: Andreas Altendorfer
description: "The Elixir/Phoenix implementation of iBoard.cc"

# build settings
port: 4000
highlighter: pygments
markdown: kramdown
permalink: pretty

baseurl: /px.iboard.cc

gems: [jekyll-coffeescript, jekyll-watch]

kramdown:
  extensions: [ "tables", "highlight", "with_toc_data" ]

defaults:
  -
    include:
      - index.html
      - posts.html
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
