title: px.iboard.cc
author: Andreas Altendorfer
description: "The Elixir/Phoenix implementation of iBoard.cc"

# build settings
port: 4000
highlighter: pygments
markdown: redcarpet
permalink: pretty

baseurl: /px.iboard.cc

defaults:
  -
    include:
      - index.html
      - posts.html
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
